##' NewFinalFilter
##'
##' This function filter the imput based on Arce et al. criteria. It should be reimplemented in order to not lost the rejected dives (ie, generating a column logical, TRUE if accepted, FALSE if rejected)
##' @title  Filtering process
##' @param fo Object of class 'data.frame' generated by NewVarsVect local function
##' @return An object of class 'data.frame' containing those dives accepted by the filter.
##' @author Fernando Arce
NewFinalFilter <- function(fo){
    Sel0 <- fo
    ## 2.1.3.4
    Sel1 <- Sel0[Sel0$order=='2.1.3.4', ] #
    ## The negatives
    Sel1 <- Sel1[Sel1$NDE <0, ]
    Sel1 <- Sel1[Sel1$d1 < .8, ]
    Sel1 <- Sel1[Sel1$propseg1 > 40, ]
    Sel1 <- Sel1[Sel1$sratio < 10, ]
    ## now the positives
    Sel11 <- Sel0[Sel0$order=='2.1.3.4', ] #
    Sel11 <- Sel11[Sel11$NDE > 0, ]
    Sel11 <- Sel11[Sel11$sdd > .13 & Sel11$sdd < .4, ]
    Sel11 <- Sel11[Sel11$t1 > 7 & Sel11$t1 < 14, ]
    Sel11 <- Sel11[Sel11$t4 > 90, ]
    Sel11 <- Sel11[Sel11$modres4 > -100 & Sel11$modres4 < 0, ]
    ## 2.1.4.3
    Sel2 <- Sel0[Sel0$order=='2.1.4.3', ]
    ## the negatives
    Sel2 <- Sel2[Sel2$NDE < 0, ]
    Sel2 <- Sel2[Sel2$d1 < .7, ]
    Sel2 <- Sel2[Sel2$d4 < .8, ]
    Sel2 <- Sel2[Sel2$t1 < 14, ]
    Sel2 <- Sel2[Sel2$propseg1 > 40, ]
    Sel2 <- Sel2[Sel2$mrratio < .15, ]
    ## the positives
    Sel22 <- Sel0[Sel0$order=='2.1.4.3', ]
    Sel22 <- Sel22[Sel22$NDE > 0, ]
    Sel22 <- Sel22[Sel22$mdepthbias < 0, ]
    Sel22 <- Sel22[Sel22$d4 < .6, ]
    Sel22 <- Sel22[Sel22$mrratio < .2, ]
    Sel22 <- Sel22[Sel22$t1 < 15, ]
    ## 2.4.1.3
    Sel3 <- Sel0[Sel0$order=='2.4.1.3', ] #
    ## the positives
    Sel3 <- Sel3[Sel3$NDE > 0, ]
    Sel3 <- Sel3[Sel3$t1 < 14, ]
    Sel3 <- Sel3[Sel3$mdepthr > 1 & Sel3$mdepthr < 1.5, ]
    Sel3 <- Sel3[Sel3$d4 < .8, ]
    Sel3 <- Sel3[Sel3$mrratio < .25, ]
    Sel3 <- Sel3[Sel3$propseg3 > 30, ]
    ## the negatives
    Sel33 <- Sel0[Sel0$order=='2.4.1.3', ] #
    Sel33 <- Sel33[Sel33$NDE < 0, ]
    Sel33 <- Sel33[Sel33$d1 < .8, ]
    Sel33 <- Sel33[Sel33$d4 < .8, ]
    Sel33 <- Sel33[Sel33$t1 < 14, ]
    Sel33 <- Sel33[Sel33$modres1 < 0, ]
    Sel33 <- Sel33[Sel33$mrratio < .15, ]
    Sel33 <- Sel33[Sel33$meand < .8, ]
    Sel33 <- Sel33[Sel33$mdepthr > .6 & Sel33$mdepthr < 1.4, ]
    ##  3.1.2.4
    Sel4 <- Sel0[Sel0$order=='3.1.2.4', ]
    ## the negatives
    Sel4 <- Sel4[Sel4$NDE < 0, ]
    Sel4 <- Sel4[Sel4$t1 < 14, ]
    Sel4 <- Sel4[Sel4$propseg1 > 40, ]
    Sel4 <- Sel4[Sel4$d1 < .6, ]
    ## the positives
    Sel44 <- Sel0[Sel0$order=='3.1.2.4', ]
    Sel44 <- Sel44[Sel44$NDE > 0, ]
    Sel44 <- Sel44[Sel44$t1 < 14, ]
    Sel44 <- Sel44[Sel44$d4 < .7, ]
    Sel44 <- Sel44[Sel44$propseg1 < 15, ]
    Sel44 <- Sel44[Sel44$d1 < .85, ]
    Sel44 <- Sel44[Sel44$mdepthr > .8 & Sel44$mdepthr < 1.5, ]
    Sel44 <- Sel44[Sel44$propseg2 > 40, ]
    ## 3.1.4.2
    Sel5<- Sel0[Sel0$order=='3.1.4.2', ]
    ## the positives
    Sel5<- Sel5[Sel5$NDE > 0, ]
    Sel5<- Sel5[Sel5$t1 < 12, ]
    Sel5<- Sel5[Sel5$sdd > .1 & Sel5$sdd < .3, ]
    Sel5<- Sel5[Sel5$mdepthr > .8 & Sel5$mdepthr < 1.3, ]
    Sel5<- Sel5[Sel5$propseg2 > 20, ]
    Sel5<- Sel5[Sel5$mrratio < .3, ]
    Sel5<- Sel5[Sel5$t4 > 90, ]
    ## the negatives
    Sel55<- Sel0[Sel0$order=='3.1.4.2', ]
    Sel55 <- Sel55[Sel55$NDE < 0, ]
    Sel55 <- Sel55[Sel55$d1 < .8, ]
    Sel55 <- Sel55[Sel55$d4 < .8, ]
    Sel55 <- Sel55[Sel55$propseg1 > 40, ]
    Sel55 <- Sel55[Sel55$sratio < 10, ]
    ## 3.2.1.4
    ## negatives
    Sel6 <- Sel0[Sel0$order=='3.2.1.4', ]
    Sel6 <- Sel6[Sel6$propseg2 > 45, ]
    Sel6 <- Sel6[Sel6$d2 < .8, ]
    Sel6 <- Sel6[Sel6$mrratio < .2, ]
    ## 3.4.1.2
    ## negatives
    Sel7 <- Sel0[Sel0$order=='3.4.1.2', ]
    Sel7 <- Sel7[Sel7$NDE < 0, ]
    Sel7 <- Sel7[Sel7$d1 < .8, ]
    Sel7 <- Sel7[Sel7$t1 < 14, ]
    Sel7 <- Sel7[Sel7$propseg3 < 20, ]
    Sel7 <- Sel7[Sel7$d4 < .8, ]
    Sel7 <- Sel7[Sel7$mrratio < .2, ]
    ## positivos
    Sel77 <- Sel0[Sel0$order=='3.4.1.2', ]
    Sel77 <- Sel77[Sel77$NDE > 0, ]
    Sel77 <- Sel77[Sel77$modres1 < 0, ]
    Sel77 <- Sel77[Sel77$d4 < .8, ]
    Sel77 <- Sel77[Sel77$t1 < 12, ]
    Sel77 <- Sel77[Sel77$t4 > 85, ]
    Sel77 <- Sel77[Sel77$sratio > 2 & Sel77$sratio < 7, ]
    ## 4.2.1.3
    ## positives
    Sel8 <- Sel0[Sel0$order=='4.2.1.3', ]
    Sel8 <- Sel8[Sel8$NDE > 0, ]
    Sel8 <- Sel8[Sel8$t1 < 8, ]
    Sel8 <- Sel8[Sel8$mdepthr > .8 & Sel8$mdepthr < 2,  ]
    Sel8 <- Sel8[Sel8$t4 > 80, ]
    ## negatives
    Sel88 <- Sel0[Sel0$order=='4.2.1.3', ]
    Sel88 <- Sel88[Sel88$NDE < 0, ]
    Sel88 <- Sel88[Sel88$d2 < .8, ]
    Sel88 <- Sel88[Sel88$t1 < 9, ]
    Sel88 <- Sel88[Sel88$d4 < .8, ]
    Sel88 <- Sel88[Sel88$mrratio < .2, ]
    Sel88 <- Sel88[Sel88$t4 > 85, ]
    out <- rbind(Sel1,Sel11,Sel2,Sel22,Sel3,Sel33,Sel4,
                 Sel44,Sel5,Sel55,Sel6,Sel7,Sel77,Sel8,
                 Sel88)
    return(out)
}


##' mas pendiente
##'
##' This function filter the imput based on Arce et al. criteria. It should be reimplemented in order to not lost the rejected dives (ie, generating a column logical, TRUE if accepted, FALSE if rejected)
##' @title  Filtering process
##' @param fo Object of class 'data.frame' generated by NewVarsVect local function
##' @return An object of class 'data.frame' containing those dives accepted by the filter.
##' @author Fernando Arce
FinalFilter <- function(fo){
    ## 2.1.3.4
    ## negatives
    Sel1 <-  fo[fo$order=='2.1.3.4' &
                  fo$NDE <0 & fo$d1 < .8 &
                  fo$propseg1 > 40 & fo$sratio < 10, ] #
    ## positives
    Sel11 <- fo[fo$order=='2.1.3.4' &
                  fo$NDE > 0 & fo$sdd > .13 & fo$sdd < .4 &
                  fo$t1 > 7 & fo$t1 < 14 & fo$t4 > 90 &
                  fo$modres4 > -100 & fo$modres4 < 0, ] #
    ## 2.1.4.3
    ## negatives
    Sel2 <-  fo[fo$order=='2.1.4.3' & fo$NDE < 0 &
                  fo$d1 < .7 & fo$d4 < .8 & fo$t1 < 14 &
                  fo$propseg1 > 40 & fo$mrratio < .15, ]
    ## the positives
    Sel22 <- fo[fo$order=='2.1.4.3' & fo$NDE > 0 &
                  fo$mdepthbias < 0 & fo$d4 < .6 &
                  fo$mrratio < .2 & fo$t1 < 15, ]
    ## 2.4.1.3
    ## positives
    Sel3 <- fo[fo$order=='2.4.1.3' & fo$NDE > 0 &
                 fo$t1 < 14 & fo$mdepthr > 1 & fo$mdepthr < 1.5 &
                 fo$d4 < .8 & fo$mrratio < .25 & fo$propseg3 > 30, ] 
    ## the negatives
    Sel33 <- fo[fo$order=='2.4.1.3' & fo$NDE < 0 &
                  fo$d1 < .8 & fo$d4 < .8 & fo$t1 < 14 &
                  fo$modres1 < 0 & fo$mrratio < .15 &
                  fo$meand < .8 & fo$mdepthr > .6 & fo$mdepthr < 1.4, ] #
    ##  3.1.2.4
    ## negatives
    Sel4 <- fo[fo$order=='3.1.2.4' & fo$NDE < 0 &
                 fo$t1 < 14 & fo$propseg1 > 40 &
                 fo$d1 < .6, ]
    ## the positives
    Sel44 <- fo[fo$order=='3.1.2.4' & fo$NDE > 0 &
                  fo$t1 < 14 & fo$d4 < .7 & fo$propseg1 < 15 &
                  fo$d1 < .85 & fo$mdepthr > .8 & fo$mdepthr < 1.5  &
                  fo$propseg2 > 40, ]
    ## 3.1.4.2
    ## positives
    Sel5<- fo[fo$order=='3.1.4.2' & fo$NDE > 0 &
                fo$t1 < 12 & fo$sdd > .1 & fo$sdd < .3 &
                fo$mdepthr > .8 & fo$mdepthr < 1.3 & fo$propseg2 > 20 &
                fo$mrratio < .3 & fo$t4 > 90, ]
    ## the negatives
    Sel55<- fo[fo$order=='3.1.4.2' & fo$NDE < 0 &
                 fo$d1 < .8 & fo$d4 < .8 &
               fo$propseg1 > 40 & fo$sratio < 10, ]
    ## 3.2.1.4
    ## negatives
    Sel6 <- fo[fo$order=='3.2.1.4' & fo$propseg2 > 45 &
               fo$d2 < .8 & fo$mrratio < .2, ]
    ## 3.4.1.2
    ## negatives
    Sel7 <- fo[fo$order=='3.4.1.2' & fo$NDE < 0 &
                 fo$d1 < .8 & fo$t1 < 14 & fo$propseg3 < 20 &
                 fo$d4 < .8 & fo$mrratio < .2, ]
    ## positivos
    Sel77 <- fo[fo$order=='3.4.1.2' & fo$NDE > 0 &
                  fo$modres1 < 0 & fo$d4 < .8 & fo$t1 < 12 &
                  fo$t4 > 85 & fo$sratio > 2 & fo$sratio < 7, ]
    ## 4.2.1.3
    ## positives
    Sel8 <- fo[fo$order=='4.2.1.3'& fo$NDE > 0 & fo$t1 < 8 &
               fo$mdepthr > .8 & fo$mdepthr < 2 & fo$t4 > 80, ]
    ## negatives
    Sel88 <- fo[fo$order=='4.2.1.3' & fo$NDE < 0 & fo$d2 < .8 &
                fo$d4 < .8 & fo$mrratio < .2 & fo$t4 > 85 &
                fo$t1 < 9, ]
    final <- rbind(Sel1,Sel11,Sel2,Sel22,Sel3,Sel33,Sel4,
                   Sel44,Sel5,Sel55,Sel6,Sel7,Sel77,Sel8,Sel88)
    return(final)
}
