##' This function filters a pre-processed data.frame. consult the referenced paper for  specific references to the procedure
##'
##'
##' @title  Filtering dives
##' @param fo Object of class 'data.frame' generated by NewVarsVect local function
##' @return An object of class 'data.frame' containing those dives accepted by the filter.
driftFilter <- function(fo){
    ## 2.1.3.4
    ## negatives
    Sel1 <-  fo[fo$order=='2.1.3.4' &
                  fo$NDE <0 & fo$d1 < .8 &
                  fo$propseg1 > 40 & fo$sratio < 10, ] #
    ## positives
    Sel11 <- fo[fo$order=='2.1.3.4' &
                  fo$NDE > 0 & fo$sdd > .13 & fo$sdd < .4 &
                  fo$t1 > 7 & fo$t1 < 14 & fo$t4 > 90 &
                  fo$modres4 > -100 & fo$modres4 < 0, ] #
    ## 2.1.4.3
    ## negatives
    Sel2 <-  fo[fo$order=='2.1.4.3' & fo$NDE < 0 &
                  fo$d1 < .7 & fo$d4 < .8 & fo$t1 < 14 &
                  fo$propseg1 > 40 & fo$mrratio < .15, ]
    ## the positives
    Sel22 <- fo[fo$order=='2.1.4.3' & fo$NDE > 0 &
                  fo$mdepthbias < 0 & fo$d4 < .6 &
                  fo$mrratio < .2 & fo$t1 < 15, ]
    ## 2.4.1.3
    ## positives
    Sel3 <- fo[fo$order=='2.4.1.3' & fo$NDE > 0 &
                 fo$t1 < 14 & fo$mdepthr > 1 & fo$mdepthr < 1.5 &
                 fo$d4 < .8 & fo$mrratio < .25 & fo$propseg3 > 30, ] 
    ## the negatives
    Sel33 <- fo[fo$order=='2.4.1.3' & fo$NDE < 0 &
                  fo$d1 < .8 & fo$d4 < .8 & fo$t1 < 14 &
                  fo$modres1 < 0 & fo$mrratio < .15 &
                  fo$meand < .8 & fo$mdepthr > .6 & fo$mdepthr < 1.4, ] #
    ##  3.1.2.4
    ## negatives
    Sel4 <- fo[fo$order=='3.1.2.4' & fo$NDE < 0 &
                 fo$t1 < 14 & fo$propseg1 > 40 &
                 fo$d1 < .6, ]
    ## the positives
    Sel44 <- fo[fo$order=='3.1.2.4' & fo$NDE > 0 &
                  fo$t1 < 14 & fo$d4 < .7 & fo$propseg1 < 15 &
                  fo$d1 < .85 & fo$mdepthr > .8 & fo$mdepthr < 1.5  &
                  fo$propseg2 > 40, ]
    ## 3.1.4.2
    ## positives
    Sel5<- fo[fo$order=='3.1.4.2' & fo$NDE > 0 &
                fo$t1 < 12 & fo$sdd > .1 & fo$sdd < .3 &
                fo$mdepthr > .8 & fo$mdepthr < 1.3 & fo$propseg2 > 20 &
                fo$mrratio < .3 & fo$t4 > 90, ]
    ## the negatives
    Sel55<- fo[fo$order=='3.1.4.2' & fo$NDE < 0 &
                 fo$d1 < .8 & fo$d4 < .8 &
               fo$propseg1 > 40 & fo$sratio < 10, ]
    ## 3.2.1.4
    ## negatives
    Sel6 <- fo[fo$order=='3.2.1.4' & fo$propseg2 > 45 &
               fo$d2 < .8 & fo$mrratio < .2, ]
    ## 3.4.1.2
    ## negatives
    Sel7 <- fo[fo$order=='3.4.1.2' & fo$NDE < 0 &
                 fo$d1 < .8 & fo$t1 < 14 & fo$propseg3 < 20 &
                 fo$d4 < .8 & fo$mrratio < .2, ]
    ## positivos
    Sel77 <- fo[fo$order=='3.4.1.2' & fo$NDE > 0 &
                  fo$modres1 < 0 & fo$d4 < .8 & fo$t1 < 12 &
                  fo$t4 > 85 & fo$sratio > 2 & fo$sratio < 7, ]
    ## 4.2.1.3
    ## positives
    Sel8 <- fo[fo$order=='4.2.1.3'& fo$NDE > 0 & fo$t1 < 8 &
               fo$mdepthr > .8 & fo$mdepthr < 2 & fo$t4 > 80, ]
    ## negatives
    Sel88 <- fo[fo$order=='4.2.1.3' & fo$NDE < 0 & fo$d2 < .8 &
                fo$d4 < .8 & fo$mrratio < .2 & fo$t4 > 85 &
                fo$t1 < 9, ]
    final <- rbind(Sel1,Sel11,Sel2,Sel22,Sel3,Sel33,Sel4,
                   Sel44,Sel5,Sel55,Sel6,Sel7,Sel77,Sel8,Sel88)
    final <- final[complete.cases(final), ]
    return(final)
}
